{% set name = "pybader" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pybader-{{ version }}.tar.gz
  sha256: edaf7fc6694290a15c8f1fec00b683f38fb51fd3d073bf5ae0ba18f4e7661751

build:
  entry_points:
    - bader = pybader.entry_points:bader
    - bader-read = pybader.entry_points:bader_read
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numba
    - numpy
    - pandas
    - python >={{ python_min }}
    - tqdm

test:
  imports:
    - pybader
  commands:
    - pip check
    - bader --help
    - bader-read --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kerrigoon/pybader
  summary: Threaded implementation of grid-based Bader charge analysis.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
